"""Dataset health & validation report — the Phase-F hardening surface.

Turns the dataset's own honesty fields (tier, review status, external-validation
performance, hypothesis-tier flags) into a machine-generated Markdown report so
coverage is visible and tracked rather than asserted.
"""

from __future__ import annotations

from collections import Counter

from .load import Dataset

# Records for which an external OS-validation metric is meaningful: clinical TGI
# and survival-link models. Growth laws, baselines, transforms, preclinical, and
# hypothesis-tier IO are excluded by construction.
_VALIDATION_ELIGIBLE_PURPOSES = {"tgi", "survival_link"}
_NON_CLINICAL_SUBSYSTEMS = {"immuno_oncology", "preclinical_translation"}


def validation_eligible(ds: Dataset):
    return [
        r
        for r in ds
        if r.purpose in _VALIDATION_ELIGIBLE_PURPOSES
        and r.subsystem not in _NON_CLINICAL_SUBSYSTEMS
    ]


def external_validation_coverage(ds: Dataset):
    """(n_validated, n_eligible, fraction) for clinical TGI / survival models."""
    eligible = validation_eligible(ds)
    validated = [r for r in eligible if r.predictive_performance]
    n = len(eligible)
    return len(validated), n, (len(validated) / n if n else 0.0)


def stats(ds: Dataset) -> dict:
    n_val, n_elig, frac = external_validation_coverage(ds)
    return {
        "version": ds.version,
        "n_records": len(ds),
        "n_citations": len(ds.citations),
        "by_subsystem": dict(sorted(ds.by_subsystem().items())),
        "by_tier": {k: ds.by_tier().get(k, 0) for k in ("A", "B", "C", "D")},
        "by_review_status": dict(sorted(ds.by_review_status().items())),
        "tier_by_subsystem": _tier_by_subsystem(ds),
        "external_validation": {"validated": n_val, "eligible": n_elig, "fraction": frac},
        "hypothesis_tier": [r.id for r in ds if r.subsystem == "immuno_oncology"],
        "verified": sum(1 for r in ds if r.review_status == "verified"),
    }


def _tier_by_subsystem(ds: Dataset) -> dict:
    table: dict = {}
    for r in ds:
        table.setdefault(r.subsystem, Counter())[r.tier] += 1
    return {sub: dict(c) for sub, c in sorted(table.items())}


def _bar(frac: float, width: int = 20) -> str:
    filled = round(frac * width)
    return "█" * filled + "░" * (width - filled)


def build_report(ds: Dataset) -> str:
    s = stats(ds)
    ev = s["external_validation"]
    lines = [
        "# Onkos dataset health report",
        "",
        "> GENERATED by `onkos report` — do not hand-edit. NOT FOR CLINICAL USE.",
        "",
        f"- **Dataset version:** {s['version']}",
        f"- **Records:** {s['n_records']}  ·  **Citations:** {s['n_citations']}",
        f"- **Verified (PDF-checked):** {s['verified']} / {s['n_records']}",
        f"- **External-validation coverage** (clinical TGI + survival models): "
        f"{ev['validated']} / {ev['eligible']}  `{_bar(ev['fraction'])}` {ev['fraction'] * 100:.0f}%",
        "",
        "## Records by subsystem",
        "",
        "| subsystem | records |",
        "| --- | --- |",
    ]
    lines += [f"| {k} | {v} |" for k, v in s["by_subsystem"].items()]

    lines += ["", "## Confidence tiers", "", "| tier | records | meaning |", "| --- | --- | --- |"]
    meaning = {
        "A": "externally validated, broad context",
        "B": "robust single trial, partial external check",
        "C": "single trial, no external validation",
        "D": "out-of-context transport, or hypothesis-tier (not predictive)",
    }
    lines += [f"| {t} | {s['by_tier'][t]} | {meaning[t]} |" for t in ("A", "B", "C", "D")]

    lines += ["", "## Tier × subsystem", "", "| subsystem | A | B | C | D |", "| --- | --- | --- | --- | --- |"]
    for sub, counts in s["tier_by_subsystem"].items():
        lines.append(
            f"| {sub} | {counts.get('A', 0)} | {counts.get('B', 0)} | "
            f"{counts.get('C', 0)} | {counts.get('D', 0)} |"
        )

    lines += ["", "## Review status", "", "| status | records |", "| --- | --- |"]
    lines += [f"| {k} | {v} |" for k, v in s["by_review_status"].items()]

    missing = [r.id for r in validation_eligible(ds) if not r.predictive_performance]
    lines += ["", "## External-validation backlog", ""]
    if missing:
        lines.append("Clinical models without a recorded external-validation metric:")
        lines += [f"- `{rid}`" for rid in sorted(missing)]
    else:
        lines.append("All eligible clinical models carry an external-validation metric.")

    if s["hypothesis_tier"]:
        lines += [
            "",
            "## Hypothesis-tier (NOT FOR PREDICTION)",
            "",
            "These records ship tier D by construction and are excluded from the clinical view:",
        ]
        lines += [f"- `{rid}`" for rid in s["hypothesis_tier"]]

    lines += [
        "",
        "## Honesty note",
        "",
        "All v0.x parameter values are illustrative and `unverified` by design. Promoting "
        "records to `verified` by reading the source PDF (especially the derivation-context "
        "and transportability claims) is the highest-leverage contribution — see CONTRIBUTING.md.",
        "",
    ]
    return "\n".join(lines)
